import type { CartServiceError } from "@/core/cart/service";
import type { SortKey } from "@/core/catalog/query";

/**
 * Textos de interface do core, iguais para todas as marcas.
 * Textos editoriais e institucionais de cada marca moram em brands/<id>/content.ts.
 */
export const copy = {
  skipToContent: "Pular para o conteúdo",
  demoNotice: "Loja de demonstração. Produtos, preços e estoque são fictícios e nenhuma compra é cobrada.",
  nav: { open: "Abrir menu", close: "Fechar menu", label: "Principal", shop: "Ver tudo" },
  search: {
    label: "Buscar produtos",
    placeholder: "Buscar",
    submit: "Buscar",
    open: "Abrir busca",
    close: "Fechar busca",
    title: (q: string) => (q ? `Resultados para “${q}”` : "Busca"),
    emptyQuery: "Digite o nome de uma peça, cor ou tecido.",
  },
  catalog: {
    all: "Todos os produtos",
    results: (n: number) => (n === 1 ? "1 produto" : `${n} produtos`),
    filters: "Filtrar",
    filtersTitle: "Filtros",
    applyFilters: "Aplicar filtros",
    clearFilters: "Limpar filtros",
    removeFilter: (label: string) => `Remover filtro ${label}`,
    size: "Tamanho",
    color: "Cor",
    price: "Preço",
    anyPrice: "Qualquer preço",
    sort: "Ordenar por",
    sortLabels: {
      relevancia: "Relevância",
      novidades: "Novidades",
      "menor-preco": "Menor preço",
      "maior-preco": "Maior preço",
    } satisfies Record<SortKey, string>,
    pagination: "Paginação",
    page: (n: number) => `Página ${n}`,
    previous: "Anterior",
    next: "Próxima",
    emptyTitle: "Nenhum produto com esses filtros",
    emptyBody: "Tire um filtro ou procure por outro termo.",
    emptyCategory: "Ainda não há produtos nesta seção.",
    backToResults: "Voltar aos resultados",
    soldOut: "Esgotado",
    fromPrice: "A partir de",
    colorsCount: (n: number) => (n === 1 ? "1 cor" : `${n} cores`),
  },
  product: {
    color: "Cor",
    size: "Tamanho",
    chooseColor: "Escolha uma cor.",
    chooseSize: "Escolha um tamanho.",
    chooseSizeButton: "Escolha um tamanho",
    chooseBoth: "Escolha cor e tamanho.",
    add: "Adicionar à sacola",
    adding: "Adicionando…",
    soldOut: "Esgotado",
    soldOutVariant: "Esta combinação está esgotada. Escolha outro tamanho ou cor.",
    lowStock: (n: number) => (n === 1 ? "Última unidade" : `Restam ${n} unidades`),
    inStock: "Disponível",
    unavailableSize: (size: string) => `${size}, esgotado`,
    quantity: "Quantidade",
    details: "Detalhes",
    composition: "Composição",
    care: "Cuidados",
    fit: "Modelagem",
    sizeGuide: "Guia de medidas",
    sizeGuideClose: "Fechar guia de medidas",
    measuresIn: "Medidas da peça em centímetros.",
    howToMeasure: "Como medir",
    gallery: (title: string) => `Fotos de ${title}`,
    imageOf: (i: number, n: number) => `Foto ${i} de ${n}`,
    selectedColor: (name: string) => `Cor selecionada: ${name}`,
    compareAt: "Preço anterior",
  },
  cart: {
    title: "Sacola",
    open: (n: number) => (n === 0 ? "Sacola vazia" : n === 1 ? "Sacola com 1 item" : `Sacola com ${n} itens`),
    close: "Fechar sacola",
    empty: "Sua sacola está vazia.",
    emptyCta: "Ver produtos",
    subtotal: "Subtotal",
    subtotalNote: "Frete e prazo são calculados na etapa de pagamento.",
    checkout: "Finalizar compra",
    viewCart: "Ver sacola completa",
    continue: "Continuar comprando",
    remove: "Remover",
    removeItem: (title: string) => `Remover ${title} da sacola`,
    increase: (title: string) => `Aumentar quantidade de ${title}`,
    decrease: (title: string) => `Diminuir quantidade de ${title}`,
    quantityOf: (title: string) => `Quantidade de ${title}`,
    lineMeta: (color: string, size: string) => [color, size ? `Tamanho ${size}` : ""].filter(Boolean).join(", "),
    added: (title: string) => `${title} foi adicionado à sacola.`,
    updated: "Sacola atualizada.",
    removed: (title: string) => `${title} saiu da sacola.`,
    clamped: (n: number) => `Só há ${n} disponível para esta peça. Ajustamos a quantidade.`,
    loading: "Carregando a sacola…",
    retry: "Tentar de novo",
    issues: {
      unavailable: "Esgotou. Remova para seguir para o pagamento.",
      insufficientStock: (n: number) =>
        n === 1 ? "Só resta 1 unidade. Ajuste a quantidade para seguir." : `Só restam ${n} unidades. Ajuste a quantidade para seguir.`,
      adjustTo: (n: number) => `Ajustar para ${n}`,
      priceChanged: (from: string, to: string) => `O preço mudou de ${from} para ${to}.`,
      acknowledge: "Aceitar novo preço",
    },
    blocked: "Resolva os avisos acima para finalizar a compra.",
  },
  errors: {
    network: "Não conseguimos falar com a loja. Verifique sua conexão e tente de novo.",
    rateLimited: "Muitas alterações seguidas. Espere alguns segundos e tente de novo.",
    generic: "Algo deu errado do nosso lado. Tente de novo em instantes.",
    cart: {
      unavailable: "Esta peça esgotou e não pode ser adicionada.",
      cart_full: "A sacola chegou ao limite de itens diferentes. Remova algum para adicionar outro.",
      invalid_quantity: "Quantidade inválida.",
      line_not_found: "Este item não está mais na sacola. Atualizamos a lista.",
      select_options: "Escolha cor e tamanho antes de adicionar.",
      product_not_found: "Não encontramos esta peça no catálogo.",
      provider_unavailable: "O catálogo não respondeu. Tente de novo em instantes.",
    } satisfies Record<CartServiceError, string>,
  },
  checkout: {
    title: "Finalizar compra",
    review: "Revise os itens",
    edit: "Editar sacola",
    pay: "Continuar para o pagamento",
    payNote: "Você será levado ao checkout seguro do provedor para informar endereço, frete e pagamento.",
    demoTitle: "Esta loja é uma demonstração",
    demoBody: [
      "Nenhum pedido foi criado e nenhum pagamento foi processado.",
      "Com um provedor configurado, a próxima etapa seria o checkout hospedado dele, onde a pessoa informa endereço, frete e forma de pagamento.",
    ],
    empty: "Não há itens para finalizar.",
    blocked: "Alguns itens mudaram desde que foram adicionados. Revise a sacola antes de continuar.",
    lineChanged: "Preço ou estoque mudou. Revise na sacola.",
    unavailable: "O checkout não respondeu. Nada foi cobrado. Tente de novo em instantes.",
  },
  notFound: {
    title: "Página não encontrada",
    body: "O endereço pode ter mudado ou o produto saiu do catálogo.",
    cta: "Ir para a loja",
  },
  error: {
    title: "Esta página não carregou",
    body: "Pode ser uma falha momentânea no catálogo. Tente de novo; se continuar, volte mais tarde.",
    retry: "Tentar de novo",
  },
  footer: {
    contact: "Atendimento",
    social: "Redes",
    credits: "Créditos das imagens",
  },
} as const;
